export const properties = [
  {
    id: 1,
    title: "Office Space in Lajpat Nagar",
    location: "Lajpat Nagar, Delhi",
    price: "₹6.3 Cr",
    pricePerSqFt: "₹29,854/sq.ft",
    area: "2,127 sq.ft",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    tags: ["Ready To Move", "Sale"],
    verified: true,
    aiEstimate: "₹7.3 Cr",
    postedBy: "Owner",
    postedAgo: "15d ago"
  },
  {
    id: 2,
    title: "Showroom in Sector 82",
    location: "Sector 82, Gurugram",
    price: "₹48.0 L",
    pricePerSqFt: "₹1,191/sq.ft",
    area: "4,029 sq.ft",
    image: "https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=800&q=80",
    tags: ["Ready To Move", "Sale"],
    verified: true,
    aiEstimate: "₹45.4 L",
    postedBy: "Owner",
    postedAgo: "18d ago"
  },
  {
    id: 3,
    title: "Office Space in Dum Dum",
    location: "Dum Dum, Kolkata",
    price: "₹6.5 Cr",
    pricePerSqFt: "₹96,263/sq.ft",
    area: "670 sq.ft",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80",
    tags: ["Ready To Move", "Sale"],
    verified: true,
    aiEstimate: "₹6.0 Cr",
    postedBy: "Owner",
    postedAgo: "21d ago"
  },
  {
    id: 4,
    title: "Luxury Villa in Whitefield",
    location: "Whitefield, Bengaluru",
    price: "₹3.2 Cr",
    pricePerSqFt: "₹12,500/sq.ft",
    area: "2,560 sq.ft",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    tags: ["Under Construction", "Sale"],
    verified: true,
    aiEstimate: "₹3.5 Cr",
    postedBy: "Builder",
    postedAgo: "2d ago"
  },
  {
    id: 5,
    title: "2 BHK Apartment in Andheri West",
    location: "Andheri West, Mumbai",
    price: "₹2.1 Cr",
    pricePerSqFt: "₹25,000/sq.ft",
    area: "840 sq.ft",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    tags: ["Ready To Move", "Sale"],
    verified: true,
    aiEstimate: "₹2.2 Cr",
    postedBy: "Dealer",
    postedAgo: "5d ago"
  },
  {
    id: 6,
    title: "Plot in Gachibowli",
    location: "Gachibowli, Hyderabad",
    price: "₹1.5 Cr",
    pricePerSqFt: "₹8,333/sq.yd",
    area: "1,800 sq.yd",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
    tags: ["New Launch", "Sale"],
    verified: false,
    aiEstimate: "₹1.6 Cr",
    postedBy: "Owner",
    postedAgo: "10d ago"
  }
];
